// DO NOT EDIT: Generated by https://github.com/seanhenry/SwiftMockGeneratorForXcode
import SwiftyKit
import AST
import Foundation
@testable import MockGenerator

class IOSpy: IO {

    var invokedCreateFile = false
    var invokedCreateFileCount = 0
    var invokedCreateFileParameters: (path: String, data: Data?, attr: [FileAttributeKey: Any]?)?
    var invokedCreateFileParametersList = [(path: String, data: Data?, attr: [FileAttributeKey: Any]?)]()
    var stubbedCreateFileResult: Bool! = false

    func createFile(atPath path: String, contents data: Data?, attributes attr: [FileAttributeKey : Any]?) -> Bool {
        invokedCreateFile = true
        invokedCreateFileCount += 1
        invokedCreateFileParameters = (path, data, attr)
        invokedCreateFileParametersList.append((path, data, attr))
        return stubbedCreateFileResult
    }
}