#!/usr/bin/env bash

javap -s -classpath lib-build/boot.jar codes/seanhenry/mockgenerator/xcode/XcodeMockGenerator
javap -s -classpath lib-build/boot.jar codes/seanhenry/mockgenerator/entities/ProtocolMethod
javap -s -classpath lib-build/boot.jar codes/seanhenry/mockgenerator/entities/ProtocolProperty
